---

- name: Install Trivy and scan Docker images
  hosts: test
  gather_facts: true
  become: true
  tasks:

    - name: Check host distribution
      debug:
        msg: "Distribution is {{ ansible_distribution }}"
    
    - name: Check host os family
      debug:
        msg: "OS family is {{ ansible_os_family }}"

    - name: Download Trivy .deb file
      get_url:
        url: https://github.com/aquasecurity/trivy/releases/download/v0.18.3/trivy_0.18.3_Linux-64bit.deb
        dest: ~/trivy_0.18.3_Linux-64bit.deb
      when: ansible_os_family == 'Debian'
  
    - name: Install Trivy .deb package
      apt:
        deb: ~/trivy_0.18.3_Linux-64bit.deb
      when: ansible_os_family == 'Debian'

    - name: Find Docker images on host
      shell: "docker images | awk 'NR!=1 {print $1,$2}' | cut -d' ' -f1,2 --output-delimiter=':'"
      register: docker_images

    - name: All running docker images
      debug: 
          msg: running all docker images {{ docker_images.stdout_lines }}

    - name: Creates directory for save the trivy outputs
      file:
        path: /tmp/trivy_output/
        state: directory
      register: trivy_output

    - name: Run Trivy scan on Docker images
      shell: trivy image {{ item }} > /tmp/trivy_output/{{ item }}.txt
      loop: "{{ docker_images.stdout_lines }}"
      register: trivy_docker_output
    
    - name: fetch the trivy output files from remote to local
      fetch:
        src: "/tmp/trivy_output/{{ item }}.txt"
        dest: "trivy-output-{{ inventory_hostname }}/{{ item | basename }}"
        flat: yes
      loop: "{{ docker_images.stdout_lines }}"
    